In [8]:
for x in range(2000,3201):
  if x % 7 == 0 and x % 5 != 0 :
    print(x)





2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996
3003
3017
3024
3031
3038
3052
3059
3066
3073
3087
3094
3101
3108
3122
3129
3136
3143
3157
3164
3171
3178
3192
3199


In [5]:
num = int(input("Enter a number: "))
factorial = 1
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,num + 1):
       factorial = factorial*i
   print("The factorial of",num,"is",factorial)

Enter a number: 7
The factorial of 7 is 5040


In [9]:
n = int(input("Enter a number: "))
x = {i : i*i for i in range(1, n+1)}
print(x)
  

Enter a number: 8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [11]:
def missing_char(str, n):
  front = str[:n]   # up to but not including n
  back = str[n+1:]  # n+1 through end of string
  return front + back
print(missing_char('kitten', 1))
print(missing_char('kitten', 0))
print(missing_char('kitten', 4))


    

ktten
itten
kittn


In [14]:
import numpy as np
arr = np.array([[0 ,1],[2 ,3],[4 ,5]])
print(arr)
list1 = arr.tolist()
print(list1)

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


In [15]:
import numpy as np
arr1 = np.array([[0,1,2]])
arr2 = np.array([[2,1,0]])
print(arr1)
print(arr2)
comat = np.cov(arr1,arr2)
print(comat)

[[0 1 2]]
[[2 1 0]]
[[ 1. -1.]
 [-1.  1.]]


In [ ]:
import math

numbers = input("Provide D: ")
numbers = numbers.split(',')

result_list = []
for D in numbers:
    Q = round(math.sqrt(2 * 50 * int(D) / 30))
    result_list.append(Q)

print(result_list)

In [16]:
import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))


100
18


In [17]:
import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))


150
22


In [18]:
import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))


180
24
